final/book/book_box/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from books import views
from rest_framework_extensions.routers import ExtendedDefaultRouter

router = ExtendedDefaultRouter()
router.register(r'books', views.BookViewSet, base_name='book')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls',
                                namespace='rest_framework')),
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api/search', views.SearchView.as_view()),
    url(r'^api/bytag', views.ByTagView.as_view()),
    url(r'^ratings/', include('star_ratings.urls',
                              namespace='ratings',
                              app_name='ratings')),
    url(r'^', include('books.urls', namespace='books')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

final/book/books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^create/$', views.create, name='create'),
  url(r'^delete/(?P<book_id>[0-9]+)/$',
      views.delete_book,
      name='delete_book'),
]

final/book/books/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils.translation import ugettext_lazy as _

from six import python_2_unicode_compatible

from star_ratings.models import Rating


@python_2_unicode_compatible
class Tag(models.Model):
    """Tag model."""

    name = models.CharField(max_length=255)

    class Meta(object):
        """Options."""

        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Book(models.Model):
    """Book model."""


    title = models.CharField(max_length=50)
    image = models.ImageField(null=True,
                              blank=True,
                              upload_to='images')
    author = models.CharField(max_length=25)
    year = models.CharField(max_length=4)
    description = models.TextField(max_length=200, 
                                   null=True)

    class Meta(object):
        """Options."""
        db_table = 'books_book'
        verbose_name = _("Book")
        verbose_name_plural = _("Books")

    def __str__(self):
        return self.title

final/book/books/views.py
import copy
import logging

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _

from rest_framework import viewsets, generics
from rest_framework.response import Response

from .form import BookForm
from .models import Book, Tag
from .serializers import BookSerializer


LOGGER = logging.getLogger(__name__)

# *************************************************************************
# ***************************** Django views ******************************
# *************************************************************************


def index(request):
    """Index view.

    :param request:
    :type request: django.http.HttpRequest
    :return:
    :rtype: django.http.HttpResponse
    """
    all_books = Book.objects.all()

    context = {
        'all_books': all_books
    }
    return render(request, 'index.html', context)


#def detail(request, book_id):
    """Detail view.

    :param request:
    :param book_id:
    :type request: django.http.HttpRequest
    :type book_id: int
    :return:
    :rtype: django.http.HttpResponse
    """
    """
    try:
        book = Book.objects.get(pk=book_id)
    except Book.DoesNotExist as err:
        raise Http404(_("Not found!"))

    context = {
        'book': book
    }
    return render(request, 'detail.html', context)
    """


def delete_book(request, book_id):
    """Delete book view.

    :param request:
    :param book_id:
    :type request: django.http.HttpRequest
    :type book_id: int
    :return:
    :rtype: django.http.HttpResponse
    """
    try:
        book = Book.objects.get(pk=book_id)
    except Book.DoesNotExist as err:
        raise Http404(_("Not found!"))

    book.delete()
    messages.success(request, _('Book successfully deleted.'))
    return redirect(reverse('books:index'))


def create(request):
    """Create book view.

    :param request:
    :type request: django.http.HttpRequest
    :return:
    :rtype: django.http.HttpResponse
    """
    LOGGER.debug("create called")

    if request.method == 'POST':
        book_form = BookForm(data=request.POST,
                                 files=request.FILES,
                                 prefix='book')

        if book_form.is_valid():
            book = book_form.save()

            messages.success(request, _('Book successfully created.'))

            return redirect(reverse('books:index'))

    else:
        book_form = BookForm(prefix='book')

    context = {
        'book_form': book_form,
    }

    return render(request, 'create.html', context)


# *************************************************************************
# ******************** API (Django REST framework) views ******************
# *************************************************************************

class BookViewSet(viewsets.ModelViewSet):
    """Book view set."""

    queryset = Book.objects.all()
    serializer_class = BookSerializer


class SearchView(generics.ListAPIView):
    """Search view set."""

    serializer_class = BookSerializer

    def get_queryset(self):
        parameter = self.request.GET.get('q', default='')
        return Book.objects.filter(title__icontains=parameter)


class ByTagView(generics.ListAPIView):
    """Book by tag view set."""

    serializer_class = BookSerializer

    def get_queryset(self):
        tag_id = self.request.GET.get('id', default='')
        return Tag.objects.get(pk=tag_id).book_set.all()

    def list(self, request, *args, **kwargs):
        tag_id = request.GET.get('id', default='')
        queryset = self.get_queryset()
        serializer = BookSerializer(queryset, many=True)
        response_data = {
            'tag_name': Tag.objects.get(pk=tag_id).name,
            'books': serializer.data
        }
        return Response(response_data)

final/book/books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Book {% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.js"></script>
    <!-- Latest compiled and minified JavaScript -->

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"/>

    {#<script src="{% static 'js/starrr.js' %}"></script>#}
    {#<script src="{% static 'js/countdown.js' %}"></script>#}
    {#<script src="{% static 'js/bootstrap.min.js' %}"></script>#}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block extrahead %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'books:index' %}"> Home </a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'books:create' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Book
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block messages %}
    {% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

{% block body %}
{% endblock %}
</body>
</html>

final/book/books/templates/create.html
{% extends 'base.html' %}
{% load i18n formset_tags %}
{% block title %}{% trans "Add a New Book" %}{% endblock %}

{% block extrahead %}
    {{ block.super }}
{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7 col-md-offset-2" >
            <h3>{% trans "Add a New Book" %}</h3>
            <div class="panel panel-default">
                <div class="panel-body">

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'books:create' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% with form=book_form %}
                            {% include 'form_template.html' %}
                        {% endwith%}

                        <hr/>


                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

final/book/books/templates/form_template.html
{% load i18n %}

{% block before_form %}{% endblock %}

{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2" for="title">{{ field.label_tag }}{% if field.field.required %}*{% endif %}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

{% block after_form %}{% endblock %}

final/book/books/templates/formset_form_template.html
{% extends "form_template.html" %}
{% load i18n %}

{% block before_form %}

<fieldset class="scheduler-border">
    {#<legend class="scheduler-border">{% trans "Ingredient form" %}</legend>#}

{% endblock %}

{% block after_form %}

    {% if with_delete_button %}
        {#<div class="hidden">{{ form.DELETE }}</div>#}
        <button type="button" class="btn btn-danger btn-xs" data-formset-delete-button>{% trans "Delete form" %}</button>
    {% endif %}

</fieldset>
{% endblock %}

final/book/books/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Home Page" %}{% endblock %}

{% load static %}

{% block body %}
<div class="container">
    <div class="row">
		<div class="well">
        <h1 class="text-center">{% trans "Books" %}</h1>
        <div class="list-group">
         {% for book in all_books %}
          <a class="list-group-item">
                <div class="media col-md-3">
                    <figure class="pull-left">
                        {% if book.image %}
                            <img  src="{{ book.image.url }}" id="pic" class="media-object img-rounded img-responsive" />
                        {% else %}
                            <img  src="{% static 'books/images/none.png' %}" id="pic" class="media-object img-rounded img-responsive" />
                        {% endif %}
                    </figure>
                </div>

                <div class="col-md-3 offset8">
                    <h5 class="list-group-item-heading"> Title: {{ book.title }} </h5>
                    <p class="list-group-item-text"> Author: {{ book.author }} </p>
                    <p id='det' iclass="list-group-item-text"> Description: {{ book.description }} </p>
                    <p class="list-group-item-text"> Year: {{ book.year }} </p>
                    <form action="{% url 'books:delete_book' book.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-trash"></span>&nbsp; Delete
                        </button>
                    </form>
                </div>
          </a>
          {% endfor %}
        </div>
        </div>
	</div>
</div>

{% endblock %}